// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VSoc.h for the primary calling header

#ifndef VERILATED_VSOC_CACHE_H_
#define VERILATED_VSOC_CACHE_H_  // guard

#include "verilated.h"

class VSoc__Syms;

class VSoc_Cache final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_cpu_req_valid,0,0);
        VL_IN8(io_cpu_req_bits_mask,7,0);
        VL_IN8(io_axi_resp_valid,0,0);
        VL_IN8(io_axi_resp_bits_choose,0,0);
        VL_OUT8(io_cpu_resp_valid,0,0);
        VL_OUT8(io_axi_req_valid,0,0);
        VL_OUT8(io_axi_req_bits_rw,0,0);
        VL_OUT8(io_fccache_state,2,0);
        VL_OUT8(io_fccache_hit,0,0);
        CData/*0:0*/ __PVT___T_321;
        CData/*0:0*/ __PVT___T_320;
        CData/*0:0*/ __PVT___T_319;
        CData/*0:0*/ __PVT___T_318;
        CData/*0:0*/ __PVT___T_317;
        CData/*0:0*/ __PVT___T_316;
        CData/*0:0*/ __PVT___T_315;
        CData/*0:0*/ __PVT___T_314;
        CData/*0:0*/ __PVT___T_311;
        CData/*0:0*/ __PVT___T_310;
        CData/*0:0*/ __PVT___T_309;
        CData/*0:0*/ __PVT___T_308;
        CData/*0:0*/ __PVT___T_307;
        CData/*0:0*/ __PVT___T_306;
        CData/*0:0*/ __PVT___T_305;
        CData/*0:0*/ __PVT___T_304;
        CData/*0:0*/ __PVT___T_301;
        CData/*0:0*/ __PVT___T_300;
        CData/*0:0*/ __PVT___T_299;
        CData/*0:0*/ __PVT___T_298;
        CData/*0:0*/ __PVT___T_297;
        CData/*0:0*/ __PVT___T_296;
        CData/*0:0*/ __PVT___T_295;
        CData/*0:0*/ __PVT___T_294;
        CData/*0:0*/ __PVT___T_291;
        CData/*0:0*/ __PVT___T_290;
        CData/*0:0*/ __PVT___T_289;
        CData/*0:0*/ __PVT___T_288;
        CData/*0:0*/ __PVT___T_287;
        CData/*0:0*/ __PVT___T_286;
        CData/*0:0*/ __PVT___T_285;
        CData/*0:0*/ __PVT___T_284;
        CData/*0:0*/ __PVT___T_281;
        CData/*0:0*/ __PVT___T_280;
        CData/*0:0*/ __PVT___T_279;
        CData/*0:0*/ __PVT___T_278;
        CData/*0:0*/ __PVT___T_277;
        CData/*0:0*/ __PVT___T_276;
        CData/*0:0*/ __PVT___T_275;
        CData/*0:0*/ __PVT___T_274;
        CData/*0:0*/ __PVT___T_271;
        CData/*0:0*/ __PVT___T_270;
        CData/*0:0*/ __PVT___T_269;
        CData/*0:0*/ __PVT___T_268;
        CData/*0:0*/ __PVT___T_267;
        CData/*0:0*/ __PVT___T_266;
        CData/*0:0*/ __PVT___T_265;
        CData/*0:0*/ __PVT___T_264;
        CData/*0:0*/ __PVT___T_261;
        CData/*0:0*/ __PVT___T_260;
        CData/*0:0*/ __PVT___T_259;
        CData/*0:0*/ __PVT___T_258;
        CData/*0:0*/ __PVT___T_257;
    };
    struct {
        CData/*0:0*/ __PVT___T_256;
        CData/*0:0*/ __PVT___T_255;
        CData/*0:0*/ __PVT___T_254;
        CData/*0:0*/ __PVT___T_251;
        CData/*0:0*/ __PVT___T_250;
        CData/*0:0*/ __PVT___T_249;
        CData/*0:0*/ __PVT___T_248;
        CData/*0:0*/ __PVT___T_247;
        CData/*0:0*/ __PVT___T_246;
        CData/*0:0*/ __PVT___T_245;
        CData/*0:0*/ __PVT___T_244;
        CData/*0:0*/ __PVT___T_241;
        CData/*0:0*/ __PVT___T_240;
        CData/*0:0*/ __PVT___T_239;
        CData/*0:0*/ __PVT___T_238;
        CData/*0:0*/ __PVT___T_237;
        CData/*0:0*/ __PVT___T_236;
        CData/*0:0*/ __PVT___T_235;
        CData/*0:0*/ __PVT___T_234;
        CData/*0:0*/ __PVT___T_231;
        CData/*0:0*/ __PVT___T_230;
        CData/*0:0*/ __PVT___T_229;
        CData/*0:0*/ __PVT___T_228;
        CData/*0:0*/ __PVT___T_227;
        CData/*0:0*/ __PVT___T_226;
        CData/*0:0*/ __PVT___T_225;
        CData/*0:0*/ __PVT___T_224;
        CData/*0:0*/ __PVT___T_221;
        CData/*0:0*/ __PVT___T_220;
        CData/*0:0*/ __PVT___T_219;
        CData/*0:0*/ __PVT___T_218;
        CData/*0:0*/ __PVT___T_217;
        CData/*0:0*/ __PVT___T_216;
        CData/*0:0*/ __PVT___T_215;
        CData/*0:0*/ __PVT___T_214;
        CData/*0:0*/ __PVT___T_211;
        CData/*0:0*/ __PVT___T_210;
        CData/*0:0*/ __PVT___T_209;
        CData/*0:0*/ __PVT___T_208;
        CData/*0:0*/ __PVT___T_207;
        CData/*0:0*/ __PVT___T_206;
        CData/*0:0*/ __PVT___T_205;
        CData/*0:0*/ __PVT___T_204;
        CData/*0:0*/ __PVT___T_201;
        CData/*0:0*/ __PVT___T_200;
        CData/*0:0*/ __PVT___T_199;
        CData/*0:0*/ __PVT___T_198;
        CData/*0:0*/ __PVT___T_197;
        CData/*0:0*/ __PVT___T_196;
        CData/*0:0*/ __PVT___T_195;
        CData/*0:0*/ __PVT___T_194;
        CData/*0:0*/ __PVT___T_191;
        CData/*0:0*/ __PVT___T_190;
        CData/*0:0*/ __PVT___T_189;
        CData/*0:0*/ __PVT___T_188;
        CData/*0:0*/ __PVT___T_187;
        CData/*0:0*/ __PVT___T_186;
        CData/*0:0*/ __PVT___T_185;
        CData/*0:0*/ __PVT___T_184;
        CData/*0:0*/ __PVT___T_181;
        CData/*0:0*/ __PVT___T_180;
        CData/*0:0*/ __PVT___T_179;
        CData/*0:0*/ __PVT___T_178;
        CData/*0:0*/ __PVT___T_177;
    };
    struct {
        CData/*0:0*/ __PVT___T_176;
        CData/*0:0*/ __PVT___T_175;
        CData/*0:0*/ __PVT___T_174;
        CData/*0:0*/ __PVT___GEN;
        CData/*0:0*/ __PVT___T_171;
        CData/*0:0*/ __PVT___T_170;
        CData/*0:0*/ __PVT___T_169;
        CData/*0:0*/ __PVT___T_168;
        CData/*0:0*/ __PVT___T_167;
        CData/*0:0*/ __PVT___T_166;
        CData/*0:0*/ __PVT___T_165;
        CData/*0:0*/ __PVT___T_164;
        CData/*0:0*/ __PVT___GEN_0;
        CData/*3:0*/ __PVT__r_count;
        CData/*3:0*/ __PVT__w_count;
        CData/*2:0*/ __PVT__state;
        CData/*0:0*/ __PVT__is_read;
        CData/*0:0*/ __PVT__is_write;
        CData/*0:0*/ __PVT___T_340;
        CData/*0:0*/ __PVT__is_alloc;
        CData/*0:0*/ __PVT__is_alloc_reg;
        CData/*7:0*/ __PVT__cpu_mask;
        CData/*0:0*/ __PVT__rw_buf;
        CData/*0:0*/ __PVT__wen;
        CData/*0:0*/ __PVT__ren;
        CData/*0:0*/ __PVT__ren_reg;
        CData/*0:0*/ __PVT___hit0_T_2;
        CData/*0:0*/ __PVT__dirty0;
        CData/*0:0*/ __PVT___T_329;
        CData/*0:0*/ __PVT___T_332;
        CData/*0:0*/ __PVT___T_337;
        CData/*0:0*/ __PVT___T_339;
        CData/*0:0*/ __PVT___GEN_14;
        CData/*2:0*/ __PVT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_48;
        CData/*3:0*/ __PVT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_49;
        IData/*31:0*/ __PVT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_50;
        IData/*23:0*/ __PVT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_51;
        CData/*0:0*/ __PVT__TagArray_ext__DOT___GEN;
        CData/*3:0*/ __PVT__TagArray_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__TagArray_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__TagArray_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_5_ext__DOT___GEN_1;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_0_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_5_ext__DOT___GEN_1;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_2_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_5_ext__DOT___GEN_1;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_4_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_5_ext__DOT___GEN_1;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_6_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_5_ext__DOT___GEN_1;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_8_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_5_ext__DOT___GEN_1;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_10_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_5_ext__DOT___GEN_1;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_12_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_5_ext__DOT___GEN_1;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_14_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_7_ext__DOT___GEN_2;
        SData/*15:0*/ __PVT__valid;
        SData/*15:0*/ __PVT__dirty;
        SData/*15:0*/ __PVT__replace;
        SData/*15:0*/ __PVT___dirty0_T;
        SData/*15:0*/ __PVT___dirty1_T;
        SData/*15:0*/ __PVT___replace_wire_T;
        SData/*15:0*/ __PVT___GEN_8;
        SData/*15:0*/ __PVT___GEN_9;
        VL_IN(io_cpu_req_bits_addr,31,0);
        VL_OUT(io_axi_req_bits_addr,31,0);
        IData/*21:0*/ __PVT___TagArray_ext_R0_data;
        IData/*21:0*/ __PVT___TagArray_ext_R1_data;
        IData/*31:0*/ __PVT__addr_reg;
        IData/*31:0*/ __PVT__addr_buf;
        VlWide<32>/*1023:0*/ __PVT__rdata0;
        VlWide<32>/*1023:0*/ __PVT__rdata1;
        VlWide<32>/*1023:0*/ __PVT__rdata0_buf;
        VlWide<32>/*1023:0*/ __PVT__rdata1_buf;
        VlWide<32>/*1023:0*/ __PVT__read;
        VlWide<32>/*1023:0*/ __PVT__wdata;
        IData/*31:0*/ __PVT___GEN_12;
        VlWide<30>/*959:0*/ __VdfgTmp_h25305f44__0;
        VL_IN64(io_cpu_req_bits_data,63,0);
    };
    struct {
        VL_IN64(io_axi_resp_bits_data,63,0);
        VL_OUT64(io_cpu_resp_bits_data,63,0);
        VL_OUT64(io_axi_req_bits_data,63,0);
        QData/*63:0*/ __PVT__cpu_data;
        QData/*63:0*/ __PVT__refill_buffer_0;
        QData/*63:0*/ __PVT__refill_buffer_1;
        QData/*63:0*/ __PVT__refill_buffer_2;
        QData/*63:0*/ __PVT__refill_buffer_3;
        QData/*63:0*/ __PVT__refill_buffer_4;
        QData/*63:0*/ __PVT__refill_buffer_5;
        QData/*63:0*/ __PVT__refill_buffer_6;
        QData/*63:0*/ __PVT__refill_buffer_7;
        QData/*63:0*/ __PVT__refill_buffer_8;
        QData/*63:0*/ __PVT__refill_buffer_9;
        QData/*63:0*/ __PVT__refill_buffer_10;
        QData/*63:0*/ __PVT__refill_buffer_11;
        QData/*63:0*/ __PVT__refill_buffer_12;
        QData/*63:0*/ __PVT__refill_buffer_13;
        QData/*63:0*/ __PVT__refill_buffer_14;
        QData/*63:0*/ __PVT__refill_buffer_15;
        VlUnpacked<IData/*21:0*/, 16> __PVT__TagArray_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_2_ext__DOT__Memory;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_2_ext__DOT__Memory;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_7_ext__DOT__Memory;
    };

    // INTERNAL VARIABLES
    VSoc__Syms* const vlSymsp;

    // CONSTRUCTORS
    VSoc_Cache(VSoc__Syms* symsp, const char* v__name);
    ~VSoc_Cache();
    VL_UNCOPYABLE(VSoc_Cache);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
