// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VSoc.h for the primary calling header

#ifndef VERILATED_VSOC_CACHE_H_
#define VERILATED_VSOC_CACHE_H_  // guard

#include "verilated.h"

class VSoc__Syms;

class VSoc_Cache final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_cpu_req_valid,0,0);
        VL_IN8(io_cpu_req_bits_mask,7,0);
        VL_IN8(io_axi_resp_valid,0,0);
        VL_OUT8(io_cpu_resp_valid,0,0);
        VL_OUT8(io_axi_req_valid,0,0);
        VL_OUT8(io_axi_req_bits_rw,0,0);
        VL_OUT8(io_fccache_state,2,0);
        VL_OUT8(io_fccache_hit,0,0);
        CData/*0:0*/ __PVT___GEN_0;
        CData/*3:0*/ __PVT__r_count;
        CData/*3:0*/ __PVT__w_count;
        CData/*2:0*/ __PVT__state;
        CData/*0:0*/ __PVT__is_read;
        CData/*0:0*/ __PVT__is_write;
        CData/*0:0*/ __PVT___T_364;
        CData/*0:0*/ __PVT__is_alloc;
        CData/*0:0*/ __PVT__is_alloc_reg;
        CData/*7:0*/ __PVT__cpu_mask;
        CData/*0:0*/ __PVT__ren;
        CData/*0:0*/ __PVT__ren_reg;
        CData/*0:0*/ __PVT___hit0_T_2;
        CData/*0:0*/ __PVT__dirty0;
        CData/*0:0*/ __PVT___T_356;
        CData/*0:0*/ __PVT___T_361;
        CData/*0:0*/ __PVT___GEN_8;
        CData/*2:0*/ __PVT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_41;
        CData/*3:0*/ __PVT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_42;
        IData/*31:0*/ __PVT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_43;
        IData/*23:0*/ __PVT__unnamedblk1__DOT__unnamedblk2__DOT___GEN_44;
        CData/*0:0*/ __PVT__TagArray_ext__DOT___GEN;
        CData/*3:0*/ __PVT__TagArray_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__TagArray_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__TagArray_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_0_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_0_7_ext__DOT___GEN;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_0_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_0_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_0_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_1_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_1_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_1_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_1_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_2_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_2_7_ext__DOT___GEN;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_2_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_2_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_2_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_3_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_3_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_3_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_3_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_4_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_4_7_ext__DOT___GEN;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_4_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_4_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_4_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_5_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_5_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_5_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_5_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_6_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_6_7_ext__DOT___GEN;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_6_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_6_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_6_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_7_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_7_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_7_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_7_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_8_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_8_7_ext__DOT___GEN;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_8_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_8_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_8_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_9_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_9_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_9_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_9_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_10_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_10_7_ext__DOT___GEN;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_10_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_10_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_10_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_11_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_11_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_11_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_11_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_12_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_12_7_ext__DOT___GEN;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_12_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_12_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_12_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_13_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_13_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_13_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_13_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_14_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_14_7_ext__DOT___GEN;
    };
    struct {
        CData/*3:0*/ __PVT__DataArray_14_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_14_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_14_7_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_0_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_0_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_0_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_0_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_1_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_1_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_1_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_1_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_2_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_2_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_2_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_2_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_3_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_3_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_3_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_3_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_4_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_4_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_4_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_4_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_5_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_5_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_5_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_5_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_6_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_6_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_6_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_6_ext__DOT___GEN_2;
        CData/*0:0*/ __PVT__DataArray_15_7_ext__DOT___GEN;
        CData/*3:0*/ __PVT__DataArray_15_7_ext__DOT___GEN_0;
        CData/*0:0*/ __PVT__DataArray_15_7_ext__DOT___GEN_1;
        CData/*3:0*/ __PVT__DataArray_15_7_ext__DOT___GEN_2;
        SData/*15:0*/ __PVT__valid;
        SData/*15:0*/ __PVT__dirty;
        SData/*15:0*/ __PVT___dirty0_T;
        VL_IN(io_cpu_req_bits_addr,31,0);
        VL_OUT(io_axi_req_bits_addr,31,0);
        IData/*21:0*/ __PVT___TagArray_ext_R0_data;
        IData/*21:0*/ __PVT___TagArray_ext_R1_data;
        IData/*31:0*/ __PVT__addr_reg;
        VlWide<32>/*1023:0*/ __PVT__rdata0;
        VlWide<32>/*1023:0*/ __PVT__rdata1;
        VlWide<32>/*1023:0*/ __PVT__rdata0_buf;
        VlWide<32>/*1023:0*/ __PVT__rdata1_buf;
        VlWide<32>/*1023:0*/ __PVT__read;
        VlWide<5>/*134:0*/ __PVT___wmask_T_2;
        VlWide<32>/*1023:0*/ __PVT__wdata;
        IData/*31:0*/ __PVT__unnamedblk1__DOT__unnamedblk2__DOT__unnamedblk4__DOT___T_1;
        IData/*31:0*/ __VdfgTmp_h082e9772__0;
        VlWide<30>/*959:0*/ __VdfgTmp_h25305f44__0;
        VL_IN64(io_cpu_req_bits_data,63,0);
        VL_IN64(io_axi_resp_bits_data,63,0);
        VL_OUT64(io_cpu_resp_bits_data,63,0);
        VL_OUT64(io_axi_req_bits_data,63,0);
        QData/*63:0*/ __PVT__cpu_data;
        QData/*63:0*/ __PVT__refill_buffer_0;
        QData/*63:0*/ __PVT__refill_buffer_1;
        QData/*63:0*/ __PVT__refill_buffer_2;
        QData/*63:0*/ __PVT__refill_buffer_3;
        QData/*63:0*/ __PVT__refill_buffer_4;
        QData/*63:0*/ __PVT__refill_buffer_5;
    };
    struct {
        QData/*63:0*/ __PVT__refill_buffer_6;
        QData/*63:0*/ __PVT__refill_buffer_7;
        QData/*63:0*/ __PVT__refill_buffer_8;
        QData/*63:0*/ __PVT__refill_buffer_9;
        QData/*63:0*/ __PVT__refill_buffer_10;
        QData/*63:0*/ __PVT__refill_buffer_11;
        QData/*63:0*/ __PVT__refill_buffer_12;
        QData/*63:0*/ __PVT__refill_buffer_13;
        QData/*63:0*/ __PVT__refill_buffer_14;
        QData/*63:0*/ __PVT__refill_buffer_15;
        VlUnpacked<IData/*21:0*/, 16> __PVT__TagArray_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_0_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_1_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_2_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_3_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_4_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_5_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_4_ext__DOT__Memory;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_6_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_7_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_8_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_9_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_10_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_11_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_12_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_13_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_4_ext__DOT__Memory;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_14_7_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_0_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_1_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_2_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_3_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_4_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_5_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_6_ext__DOT__Memory;
        VlUnpacked<CData/*7:0*/, 16> __PVT__DataArray_15_7_ext__DOT__Memory;
    };

    // INTERNAL VARIABLES
    VSoc__Syms* const vlSymsp;

    // CONSTRUCTORS
    VSoc_Cache(VSoc__Syms* symsp, const char* v__name);
    ~VSoc_Cache();
    VL_UNCOPYABLE(VSoc_Cache);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
